spring:
  data:
    mongodb:
      auto-index-creation: true

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions: []

available-currencies:
  codes:
    - USD
    - EUR
    - PLN

exchange-rates:
  rates:
    - base-currency: USD
      target-currency: EUR
      rate: 0.85
    - base-currency: USD
      target-currency: PLN
      rate: 3.75
    - base-currency: EUR
      target-currency: USD
      rate: 1.18
    - base-currency: EUR
      target-currency: PLN
      rate: 4.42
    - base-currency: PLN
      target-currency: USD
      rate: 0.27
    - base-currency: PLN
      target-currency: EUR
      rate: 0.23
